import sys
import subprocess
import re
import collections
from pprint import pprint
import difflib
import itertools
import operator

PREFIX = '//$'

def print_llvm_objdump_version(llvm_objdump_path):
    llvm_objdump_version = subprocess.run([llvm_objdump_path, '--version'], capture_output=True, text=True)
    if len(llvm_objdump_version.stderr) > 0 or llvm_objdump_version.returncode != 0:
        sys.exit(1)
    print('llvm-objdump version output:\n', ''.join(llvm_objdump_version.stdout.splitlines(True)[:2]))

def llvm_objdump_disassembly(llvm_objdump_path, target):
    disasm_result = subprocess.run([llvm_objdump_path, '-d', '--no-leading-addr', '--no-show-raw-insn', '--demangle', '--x86-asm-syntax=intel', target], capture_output=True, text=True)
    if len(disasm_result.stderr) > 0:
        print('Disassembly error: {} (return code: {})'.format(disasm_result.stderr, disasm_result.returncode))
        sys.exit(1)
    if disasm_result.returncode != 0:
        print('Disassembly return code: {}'.format(disasm_result.returncode))
        sys.exit(1)
    return disasm_result.stdout

def parse_disassembly(raw_string):
    disasm_target_list = []
    function_name_pattern = re.compile(r'<.*?(\S+)\(.*\)>')
    instruction_pattern = re.compile(r'\s+(.*)', re.DOTALL)
    decimal_number = re.compile(r'(\W|\A)(\d+)(\W|\Z)')

    for line in raw_string.splitlines():
        if function_name := re.match(function_name_pattern, line):
            disasm_target_list.append((function_name[1], []))
        elif len(disasm_target_list) != 0 and (instruction := re.match(instruction_pattern, line)):
            # Filter out endbr64/32 that gets generated by GCC and nop that gets generated for alignment
            if ('endbr64' in instruction[1]) or ('endbr32' in instruction[1]) or ('nop' in instruction[1]):
                continue
            cleaned_instruction = instruction[1].partition('#')[0].strip().replace('\t', ' ')
            if len(cleaned_instruction) == 0:
                continue
            converted_instruction = re.sub(decimal_number, lambda m: (m[1] + hex(int(m[2])) + m[3]), cleaned_instruction)

            disasm_target_list[-1][1].append(converted_instruction + '\n')

    return dict(disasm_target_list)

def parse_compilers(compilers):
    if compilers is None:
        return None

    return [operator.itemgetter(0, 2)(compiler.partition(' ')) for compiler in compilers.lower().split(',')]

def parse_expected_disassembly(file_path):
    function_pattern = re.compile(r'@(.+?)\s*(?:{(.+)})?\s*:')
    
    expected_disasm = []
    with open(file_path) as src_file:
        section = None
        for idx, line in enumerate(src_file, start=1):
            exp = line.partition(PREFIX)[2].strip()
            if exp == '': continue

            if fn := function_pattern.match(exp):
                fn_name, compilers = fn[1], fn[2]

                if section is not None:
                    expected_disasm.append(section)

                section = (fn_name, parse_compilers(compilers), [])
            else:
                section[2].append((idx, exp + '\n'))
        if section is not None:
            expected_disasm.append(section)

    return expected_disasm

def difference_with_line_numbers(difference, line_numbers):
    index = 0
    max_number_length = max(len(str(line_num)) for line_num in line_numbers)
    for line in difference:
        code = line[:2]

        if code in ('  ', '+ '):
            yield '{} {}'.format(str(line_numbers[index]).ljust(max_number_length), line)
            index += 1
        else:
            yield '{} {}'.format(' ' * max_number_length, line)

def parse_compiler_version(version_string):
    splitted_version_string = version_string.split('.')
    return tuple(itertools.chain(map(int, splitted_version_string), [0] * (4 - len(splitted_version_string))))

def match_compiler(compiler_needle, compiler_haystack):
    current_compiler_name, current_compiler_raw_ver = compiler_needle
    current_compiler_ver = parse_compiler_version(current_compiler_raw_ver)

    for name, version in compiler_haystack:
        if name != current_compiler_name: continue

        if len(version) == 0:
            return True
        elif version[0] == '<':
            if current_compiler_ver < parse_compiler_version(version[1:]):
                return True
        elif version[0] == '>':
            if current_compiler_ver > parse_compiler_version(version[1:]):
                return True
        else:
            if current_compiler_ver == parse_compiler_version(version):
                return True
    return False

def check_disassembly(expected, received, current_compiler):
    is_successful = True
    checked_function = 0

    differ = difflib.Differ()
    for fn_name, compilers, expected_asm in expected:
        if (resulted_asm := received.get(fn_name, None)) is None:
            print('\nUnknown function name: "{}"\nList of known function names: {}\n'.format(fn_name, ", ".join(received.keys())))
            sys.exit(1)

        if compilers is None:
            used_compilers = itertools.chain.from_iterable([
                other_compilers for _, other_compilers, _ in filter(lambda x: x[0] == fn_name and x[1] is not None, expected)
            ])
            if match_compiler(current_compiler, used_compilers):
                continue
                
        elif not match_compiler(current_compiler, compilers):
            continue

        checked_function += 1

        difference = list(differ.compare(resulted_asm, [asm_and_line[1] for asm_and_line in expected_asm]))
        if any(line[:2] == '+ ' for line in difference):
            print('{}:\n{}'.format(fn_name, ''.join(difference_with_line_numbers(difference, [asm_and_line[0] for asm_and_line in expected_asm]))))
            is_successful = False

    if not is_successful:
        sys.exit(1)
    else:
        print('\nSuccessfully completed (functions checked: {})\n'.format(checked_function))

def main():
    llvm_objdump_path = sys.argv[1].strip()
    target_path = sys.argv[2].strip()
    source_path = sys.argv[3].strip()
    current_compiler = (sys.argv[4].strip().lower(), sys.argv[5].strip())

    print('Compiler name: "{}", version: "{}"\n'.format(current_compiler[0], current_compiler[1]))

    print_llvm_objdump_version(llvm_objdump_path)
    raw_disassembly = llvm_objdump_disassembly(llvm_objdump_path, target_path)
    received_disassembly = parse_disassembly(raw_disassembly)
    expected_disassembly = parse_expected_disassembly(source_path)
    check_disassembly(expected_disassembly, received_disassembly, current_compiler)

if __name__ == '__main__':
    main()
