import sys
import subprocess
import re
import collections
from pprint import pprint

PREFIX = '//$'

def print_llvm_objdump_version(llvm_objdump_path):
    llvm_objdump_version = subprocess.run([llvm_objdump_path, '--version'], capture_output=True, text=True)
    if len(llvm_objdump_version.stderr) > 0 or llvm_objdump_version.returncode != 0:
        sys.exit(1)
    print('llvm-objdump version output:\n', ''.join(llvm_objdump_version.stdout.splitlines(True)[:2]))

def llvm_objdump_disassembly(llvm_objdump_path, target):
    disasm_result = subprocess.run([llvm_objdump_path, '-d', '--no-leading-addr', '--no-show-raw-insn', '--demangle', '--x86-asm-syntax=intel', target], capture_output=True, text=True)
    if len(disasm_result.stderr) > 0:
        print('Disassembly error: {} (return code: {})'.format(disasm_result.stderr, disasm_result.returncode))
        sys.exit(1)
    if disasm_result.returncode != 0:
        print('Disassembly return code: {}'.format(disasm_result.returncode))
        sys.exit(1)
    return disasm_result.stdout

def parse_disassembly(raw_string):
    disasm_target_list = []
    function_name_pattern = re.compile(r'<.*?(\S+)\(.*\)>')
    instruction_pattern = re.compile(r'\s+(.*)', re.DOTALL)
    decimal_number = re.compile(r'(\W|\A)(\d+)(\W|\Z)')

    for line in raw_string.splitlines():
        if function_name := re.match(function_name_pattern, line):
            disasm_target_list.append((function_name[1], []))
        elif len(disasm_target_list) != 0 and (instruction := re.match(instruction_pattern, line)):
            # Filter out endbr64/32 that gets generated by GCC and nop that gets generated for alignment
            if ('endbr64' in instruction[1]) or ('endbr32' in instruction[1]) or ('nop' in instruction[1]):
                continue
            cleaned_instruction = instruction[1].partition('#')[0].strip().replace('\t', ' ')
            if len(cleaned_instruction) == 0:
                continue
            converted_instruction = re.sub(decimal_number, lambda m: (m[1] + hex(int(m[2])) + m[3]), cleaned_instruction)

            disasm_target_list[-1][1].append(converted_instruction)

    return dict(disasm_target_list)

def parse_expected_disassembly(file_path):
    function_pattern = re.compile(r'@(.+?)\s*{(.+)}\s*:')

    expected_disasm = []
    with open(file_path) as src_file:
        section = None
        for idx, line in enumerate(src_file, start=1):
            exp = line.partition(PREFIX)[2].strip()
            if exp == '': continue

            if fn := function_pattern.match(exp):
                fn_name, compilers = fn[1], fn[2]
                if compilers is None:
                    print('Invalid compiler attribute in function name. Line: {}, Function: "{}"'.format(idx, fn_name))
                    sys.exit(1)

                if section is not None: expected_disasm.append(section)
                section = (fn_name, (compilers.lower().split(','), []))
            else:
                section[1][1].append((idx, exp))
        if section is not None:
            expected_disasm.append(section)

    return expected_disasm

def check_disassembly(expected, received, current_compiler):
    is_successful = True
    checked_function = 0

    for fn_name, (compilers, expected_asm) in expected:
        is_successful_current_iteration = True
        resulted_asm = received.get(fn_name, None)
        if resulted_asm is None:
            print('\nUnknown function name: "{}"\nList of known function names: {}\n'.format(fn_name, ", ".join(received.keys())))
            sys.exit(1)

        if current_compiler not in compilers:
            continue

        checked_function += 1

        for (line_number, expected_asm_line), resulted_asm_line in zip(expected_asm, resulted_asm):
            if expected_asm_line != resulted_asm_line:
                print('Line: {}\nFunction: "{}"\n Expected: "{}"\n Received: "{}"\n'.format(line_number, fn_name, expected_asm_line, resulted_asm_line))
                is_successful_current_iteration = False

        if len(expected_asm) > len(resulted_asm):
            print('Function: "{}"\n Expected too many instructions: {}\n Received: {}\n'.format(fn_name, len(expected_asm), len(resulted_asm)))
            is_successful_current_iteration = False
        elif len(expected_asm) < len(resulted_asm):
            print('Function: "{}"\n Received too many instructions: {}\n Expected: {}\n'.format(fn_name, len(resulted_asm), len(expected_asm)))
            is_successful_current_iteration = False

        if not is_successful_current_iteration:
            print('Full received assembly:\n {}'.format("\n ".join(resulted_asm)))
            is_successful = False

    if not is_successful:
        sys.exit(1)
    else:
        print('\nSuccessfully completed (functions checked: {})\n'.format(checked_function))

def main():
    llvm_objdump_path = sys.argv[1].strip()
    target_path = sys.argv[2].strip()
    source_path = sys.argv[3].strip()
    current_compiler = sys.argv[4].strip().lower()

    print_llvm_objdump_version(llvm_objdump_path)
    raw_disassembly = llvm_objdump_disassembly(llvm_objdump_path, target_path)
    received_disassembly = parse_disassembly(raw_disassembly)
    expected_disassembly = parse_expected_disassembly(source_path)
    check_disassembly(expected_disassembly, received_disassembly, current_compiler)

if __name__ == '__main__':
    main()
