name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2022 ]
        generator: [ "Unix Makefiles", "Visual Studio 17 2022" ]
        exclude:
          - os: ubuntu-latest
            generator: "Visual Studio 17 2022"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "${{ matrix.generator }}"

    - name: Build
      run: cmake --build build --config Debug

    - name: Test
      run: ctest --test-dir build/ --output-on-failure -j 2
